#
# Authors:     PN
# Maintainers: PN
# Copyright:   2020, UWCHR, GPL v2 or later
# ============================================
# nwdc-seg/docs/Makefile

.PHONY: all clean

all: \
	index.html

index.html: \
		../write/output/nwdc.html
	cp ../write/output/nwdc.html index.html